version: '2'

services:
  app:
    image: 'telescope:latest'
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/telescope-admin
      - SPRING_DATASOURCE_USERNAME=telescope-admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=telescope-admin
      - POSTGRES_PASSWORD=admin