version: '2'

services:
  keycloak:
    image: jboss/keycloak:4.8.3.Final
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    networks:
      - tc-net
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloakdb
    networks:
      - tc-net
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  tc-net:
    driver: bridge